### ISSUE TITLE
Children in CARES gallery page broken

### ISSUE THREAD

**Issue by sabineloos** [datartathon/datartathon.github.io#4]
![image](https://user-images.githubusercontent.com/30131176/111831098-20bde380-88ac-11eb-983b-d84279a882cf.png)

The page here is broken, says 403 Forbidden: http://datartathon.com/projects/2020-jackie-cares

**Comment by arogyakoirala** [comment]
This probably has to do with the website where this graphic is hosted. I've reached out to Jackie.

**Comment by arogyakoirala** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/24402285/112706507-bc62db80-8ecc-11eb-9dda-01f1cf73289c.png)
